spring.application.name=SalonSpa
spring.profiles.active=postgres

# PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/salonspa_webflux
spring.r2dbc.username=postgres
spring.r2dbc.password=root
spring.sql.init.mode=always

logging.level.org.springframework.r2dbc=DEBUG

# MongoDB
# spring.mongodb.host=localhost
# spring.mongodb.port=27017
# spring.mongodb.database=user_webflux

# app.database=mongo



